version: "3.9"

services:

  db:
    image: postgres
    container_name: db
    # volumes:
    #   - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $RAILS_DB_NAME
      POSTGRES_USER: $RAILS_DB_USER
      POSTGRES_PASSWORD: $RAILS_DB_PASS

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_DB_HOST: $RAILS_DB_HOST
      RAILS_DB_NAME: $RAILS_DB_NAME
      RAILS_DB_USER: $RAILS_DB_USER
      RAILS_DB_PASS: $RAILS_DB_PASS
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db

# volumes:
#   db-data:
#   app-data:
